### ISSUE TITLE
No way to stop a running script

### ISSUE THREAD

**Issue by watson** [heroku/hk#187]
There doesn't seem to be a way to stop a running script (the equivalent of `heroku ps:stop run.3291`), or am I missing something?

**Comment by bgentry** [comment]
Hi @watson. The Heroku API exposes a single action to either restart a persistent process (such as `web.1`) or, in the case of a one-off `run` process, to simply kill it: https://devcenter.heroku.com/articles/platform-api-reference#dyno-restart

So you can just run `hk restart run.3291` and it would kill that dyno altogether.

**Comment by watson** [comment]
Ah, maybe it should be noted in the docs then. Preferably both in the `hk help commands` and the `hk help restart` docs. That way it's easy to find when searching: `hk help commands | grep stop`

**Comment by bgentry** [comment]
not a bad idea :)

**Comment by watson** [comment]
Should I make a pull request?

**Comment by watson** [comment]
@bgentry went ahead and did it
