### ISSUE TITLE
hk and heroku creates different apps (hk with meteor fails)

### ISSUE THREAD

**Issue by ivankravchenko** [heroku/hk#191]
On investigating [this issue](https://github.com/AdmitHub/meteor-buildpack-horse/issues/8), I've discovered, that app created with `hk create` is little bit different that app created with `heroku create`. They look just the same (same region, same cedar-14 stack) but pushing fresh meteor app with [this buildpack](https://github.com/AdmitHub/meteor-buildpack-horse) to `hk create`'d app always fails without any clue in any logs.

As of I cannot figure out where is the difference and no any clues in logs, I can only propose this way to recreate problem:

1. Create new Meteor app: `meteor create new-meteor-app ; cd new-meteor-app`.
2. `hk create` app and follow [buildpack's instructions](https://github.com/AdmitHub/meteor-buildpack-horse).
3. When you do `git push heroku master`, get `Push rejected, failure creating release` error.

Then do the same, but create app with `heroku create`. That app works.

**Comment by dickeyxxx** [comment]
you're missing the ssh key in heroku

**Comment by ivankravchenko** [comment]
@dickeyxxx , what do you mean? I believe I have working ssh key auth setup :)

**Comment by dickeyxxx** [comment]
`heroku create` uses http-git, `hk create` uses ssh, that's why you're seeing the auth failure. You can try to add your ssh key, but it's probably easier just to use the http-git remote that `heroku` uses (and not use ssh at all).

I think http-git is also a bit faster.

**Comment by ivankravchenko** [comment]
This is not auth failure.
Please review `git push heroku master` log:
```
$ git push heroku master
-----> Fetching custom git buildpack... done
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.0.3.1 has been installed in your home directory (~/.meteor).

...

-----> Adding PATH environment
-----> Running extras
-----> Adding MONGOHQ_URL -> MONGO_URL env
-----> Adding MONGOLAB_URI -> MONGO_URL env
-----> Installing phantomjs.
-----> Discovering process types
       Procfile declares types   -> (none)
       Default types for Node.js -> web

-----> Compressing... done, 22.1MB
-----> Launching... 
 !     Push rejected, failure creating release

To git@heroku.com:meteor-heroku-deploy-test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:meteor-heroku-deploy-test.git'
```

**Comment by dickeyxxx** [comment]
can you submit a support ticket? This isn't hk-related
