### ISSUE TITLE
Future of hk

### ISSUE THREAD

**Issue by koenpunt** [heroku/hk#199]
Is there any plan of further development of hk, or has all efforts been moved to the original Heroku cli?

I still like the speed of hk, but using `hk run` has stopped working for me some time ago (it never attaches). 

Is this a thing expected to be fixed, or shouldn't I get my hopes up?

**Comment by dickeyxxx** [comment]
This project is essentially dead. We learned a lot of lessons from it though and applied it to a different Go CLI that the Toolbelt is currently migrating to under the hood. `hk` was a bit too simplified and would not have been a full solution to replace the Toolbelt. It shares the same command syntax as the old one and performs almost as fast:

```
$ time ~/.heroku/heroku-cli  domains --app heroku-npm
=== heroku-npm Heroku Domain
heroku-npm.herokuapp.com

        0.75 real         0.22 user         0.03 sys
$ time hk domains --app heroku-npm
heroku-npm.herokuapp.com
        0.59 real         0.05 user         0.01 sys
```

github.com/heroku/heroku-cli

**Comment by dpiddy** [comment]
Perhaps a README update is in order?

**Comment by koenpunt** [comment]
@dpiddy exactly what I was thinking :+1:

**Comment by koenpunt** [comment]
Solution: `echo alias hk="heroku" >> .zshrc`

**Comment by dickeyxxx** [comment]
@dpiddy probably, we haven't had this conversation yet though. I'll start one and barring any objections officially deprecate it.
